/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.TictacToe;

import javax.swing.JToggleButton;

/**
 *
 * @author FamilyLaptop
 */
public class TicTacToe extends javax.swing.JFrame {
    public String[][] array1;
    public static String[][] ticTacToe = {{"","",""},
                                          {"","",""},
                                          {"","",""}};
    //public void determineWin(String[][] array1);
    public static int playerNum = 1;

    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnTL = new javax.swing.JToggleButton();
        btnTM = new javax.swing.JToggleButton();
        btnTR = new javax.swing.JToggleButton();
        btnML = new javax.swing.JToggleButton();
        btnMM = new javax.swing.JToggleButton();
        btnMR = new javax.swing.JToggleButton();
        btnBL = new javax.swing.JToggleButton();
        btnBM = new javax.swing.JToggleButton();
        btnBR = new javax.swing.JToggleButton();
        btnReset = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Player 1's Turn");

        btnTL.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btnTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTLActionPerformed(evt);
            }
        });

        btnTM.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btnTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTMActionPerformed(evt);
            }
        });

        btnTR.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btnTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTRActionPerformed(evt);
            }
        });

        btnML.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btnML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMLActionPerformed(evt);
            }
        });

        btnMM.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btnMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMMActionPerformed(evt);
            }
        });

        btnMR.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btnMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMRActionPerformed(evt);
            }
        });

        btnBL.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btnBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBLActionPerformed(evt);
            }
        });

        btnBM.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btnBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBMActionPerformed(evt);
            }
        });

        btnBR.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        btnBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBRActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnTL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnML, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnBL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnML, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBL, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBR, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTLActionPerformed
     
        if ("".equals(ticTacToe[0][0])) {
            if (playerNum == 1) {
                ticTacToe[0][0] = "X";
                btnTL.setText("X");
                playerNum = 2;
                jLabel2.setText("Player " + playerNum + "'s turn");
            } else if (playerNum == 2){
                ticTacToe[0][0] = "O";
                btnTL.setText("O");
                playerNum = 1;
                jLabel2.setText("Player " + playerNum + "'s turn");
            }
        }
        determineWin(ticTacToe);
    }//GEN-LAST:event_btnTLActionPerformed

    //==========================================================================
    
    private void btnTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTMActionPerformed
        if ("".equals(ticTacToe[0][1])){
            if (playerNum == 1) {
                ticTacToe[0][1] = "X";
                btnTM.setText("X");
                playerNum = 2;
                jLabel2.setText("Player " + playerNum + "'s turn");
            } else {
                ticTacToe[0][1] = "O";
                btnTM.setText("O");
                playerNum = 1;
                jLabel2.setText("Player " + playerNum + "'s turn");
            }
        }
        determineWin(ticTacToe);
    }//GEN-LAST:event_btnTMActionPerformed

    //==========================================================================
    
    private void btnTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTRActionPerformed
       if ("".equals(ticTacToe[0][2])){
           if (playerNum == 1) {
               ticTacToe[0][2] = "X";
               btnTR.setText("X");
               playerNum = 2;
               jLabel2.setText("Player " + playerNum + "'s turn");
            } else {
               ticTacToe[0][2] = "O";
               btnTR.setText("O");
               playerNum = 1;
               jLabel2.setText("Player " + playerNum + "'s turn");
            }
       }      
       determineWin(ticTacToe);
    }//GEN-LAST:event_btnTRActionPerformed

    //==========================================================================
    
    private void btnMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMLActionPerformed
        if ("".equals(ticTacToe[1][0])){
            if (playerNum == 1) {
                ticTacToe[1][0] = "X";
                btnML.setText("X");
                playerNum = 2;
                jLabel2.setText("Player " + playerNum + "'s turn");
            } else {
                ticTacToe[1][0] = "O";
                btnML.setText("O");
                playerNum = 1;
                jLabel2.setText("Player " + playerNum + "'s turn");
            }
        }
        determineWin(ticTacToe);
    }//GEN-LAST:event_btnMLActionPerformed

    //==========================================================================
    
    private void btnMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMMActionPerformed
        if ("".equals(ticTacToe[1][1])){
            if (playerNum == 1) {
                ticTacToe[1][1] = "X";
                btnMM.setText("X");
                playerNum = 2;
                jLabel2.setText("Player " + playerNum + "'s turn");
            } else {
                ticTacToe[1][1] = "O";
                btnMM.setText("O");
                playerNum = 1;
                jLabel2.setText("Player " + playerNum + "'s turn");
            }
        }
        determineWin(ticTacToe);
    }//GEN-LAST:event_btnMMActionPerformed

    //==========================================================================
    
    private void btnMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMRActionPerformed
        if ("".equals(ticTacToe[1][2])){
            if (playerNum == 1) {
                ticTacToe[1][2] = "X";
                btnMR.setText("X");
                playerNum = 2;
                jLabel2.setText("Player " + playerNum + "'s turn");
            } else {
                ticTacToe[1][2] = "O";
                btnMR.setText("O");
                playerNum = 1;
                jLabel2.setText("Player " + playerNum + "'s turn");
            }
        }
        determineWin(ticTacToe);
    }//GEN-LAST:event_btnMRActionPerformed

    //==========================================================================
    
    private void btnBLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBLActionPerformed
        if ("".equals(ticTacToe[2][0])){
            if (playerNum == 1) {
                ticTacToe[2][0] = "X";
                btnBL.setText("X");
                playerNum = 2;
                jLabel2.setText("Player " + playerNum + "'s turn");
            } else {
                ticTacToe[2][0] = "O";
                btnBL.setText("O");
                playerNum = 1;
                jLabel2.setText("Player " + playerNum + "'s turn");
            }
        }
        determineWin(ticTacToe);
    }//GEN-LAST:event_btnBLActionPerformed

    //==========================================================================
    
    private void btnBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBMActionPerformed
        if ("".equals(ticTacToe[2][1])){
            if (playerNum == 1) {
                ticTacToe[2][1] = "X";
                btnBM.setText("X");
                playerNum = 2;
                jLabel2.setText("Player " + playerNum + "'s turn");
            } else {
                ticTacToe[2][1] = "O";
                btnBM.setText("O");
                playerNum = 1;
                jLabel2.setText("Player " + playerNum + "'s turn");
            }
        }
        determineWin(ticTacToe);
    }//GEN-LAST:event_btnBMActionPerformed

    //==========================================================================
    
    private void btnBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBRActionPerformed
        if ("".equals(ticTacToe[2][2])){
            if (playerNum == 1) {
                ticTacToe[2][2] = "X";
                btnBR.setText("X");
                playerNum = 2;
                jLabel2.setText("Player " + playerNum + "'s turn");
            } else {
                ticTacToe[2][2] = "O";
                btnBR.setText("O");
                playerNum = 1;
                jLabel2.setText("Player " + playerNum + "'s turn");
            }
        }
        determineWin(ticTacToe);
    }//GEN-LAST:event_btnBRActionPerformed

    //==========================================================================
    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
       btnTL.setText("");
       btnTM.setText("");
       btnTR.setText("");
       btnML.setText("");
       btnMM.setText("");
       btnMR.setText("");
       btnBL.setText("");
       btnBM.setText("");
       btnBR.setText("");
       
       for (int i = 0; i < 3; i++) {
           for (int j = 0; j < 3; j++) {
               ticTacToe[i][j] = "";
           }
       }
       
       btnTL.setEnabled(true);
       btnTM.setEnabled(true);
       btnTR.setEnabled(true);
       btnML.setEnabled(true);
       btnMM.setEnabled(true);
       btnMR.setEnabled(true);
       btnBL.setEnabled(true);
       btnBM.setEnabled(true);
       btnBR.setEnabled(true);

       btnTL.setSelected(false);
       btnTM.setSelected(false);
       btnTR.setSelected(false);
       btnML.setSelected(false);
       btnMM.setSelected(false);
       btnMR.setSelected(false);
       btnBL.setSelected(false);
       btnBM.setSelected(false);
       btnBR.setSelected(false);       
       
       playerNum = 1;
       jLabel2.setText("Player 1's Turn");
    }//GEN-LAST:event_btnResetActionPerformed

    //==========================================================================
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }
    
    //==========================================================================
    
    public void determineWin(String[][] array1) {
        if (ticTacToe[0][0].equals(ticTacToe[0][1]) && ticTacToe[0][1].equals(ticTacToe[0][2]) && !"".equals(ticTacToe[0][1])) {//ttt           
            Win();
        } else if (ticTacToe[1][0].equals(ticTacToe[1][1]) && ticTacToe[1][1].equals(ticTacToe[1][02]) && !"".equals(ticTacToe[1][1])) {///mmm
            Win();
        } else if (ticTacToe[2][0].equals(ticTacToe[2][1]) && ticTacToe[2][1].equals(ticTacToe[2][2]) && !"".equals(ticTacToe[2][1])) {///bbb
            Win();
        } else if (ticTacToe[0][0].equals(ticTacToe[1][0]) && ticTacToe[1][0].equals(ticTacToe[2][0]) && !"".equals(ticTacToe[1][0])) {///lll
            Win();
        } else if (ticTacToe[0][1].equals(ticTacToe[1][1]) && ticTacToe[1][1].equals(ticTacToe[2][1]) && !"".equals(ticTacToe[1][1])) {//mmm
            Win();
        } else if (ticTacToe[0][2].equals(ticTacToe[1][2]) && ticTacToe[1][2].equals(ticTacToe[2][2]) && !"".equals(ticTacToe[1][2])) {//rrr
            Win();
        } else if (ticTacToe[0][0].equals(ticTacToe[1][1]) && ticTacToe[1][1].equals(ticTacToe[2][2]) && !"".equals(ticTacToe[1][1])) {
            Win();
        } else if (ticTacToe[2][0].equals(ticTacToe[1][1]) && ticTacToe[1][1].equals(ticTacToe[0][2]) && !"".equals(ticTacToe[1][1])) {
            Win();
        }
    }
    
    //00 01 02
    //10 11 12
    //20 21 22
    
    //==========================================================================
    
    public void Win(){
        btnTL.setEnabled(false);
        btnTM.setEnabled(false);
        btnTR.setEnabled(false);
        btnML.setEnabled(false);
        btnMM.setEnabled(false);
        btnMR.setEnabled(false);
        btnBL.setEnabled(false);
        btnBM.setEnabled(false);
        btnBR.setEnabled(false);
                
        if (playerNum == 1) {
            playerNum = 2;
        } else {
            playerNum = 1;
        }
        jLabel2.setText("Player " + playerNum + " wins!!!");        
    }
    
    //==========================================================================

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBL;
    private javax.swing.JToggleButton btnBM;
    private javax.swing.JToggleButton btnBR;
    private javax.swing.JToggleButton btnML;
    private javax.swing.JToggleButton btnMM;
    private javax.swing.JToggleButton btnMR;
    private javax.swing.JToggleButton btnReset;
    private javax.swing.JToggleButton btnTL;
    private javax.swing.JToggleButton btnTM;
    private javax.swing.JToggleButton btnTR;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
